import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// eslint-disable-next-line react-refresh/only-export-components
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.about': 'About',
    'nav.packs': 'The Packs',
    'nav.services': 'Services',
    'nav.results': 'Results',
    'nav.contact': 'Contact',
    'nav.bookCall': 'Book Discovery Call',
    
    // Hero Section
    'hero.badge': 'Growth Accelerator',
    'hero.title1': 'We Don\'t',
    'hero.title2': 'Market',
    'hero.title3': 'We',
    'hero.title4': 'Accelerate Growth.',
    'hero.subtitle': 'DevHelp transforms your ideas into real results through innovative web solutions, strategic guidance, and a performance-driven mindset. We\'re not just another agency — we\'re your growth partner.',
    'hero.cta1': 'Let\'s Accelerate',
    'hero.cta2': 'Book Discovery Call',
    
    // About Section
    'about.title1': 'Beyond Marketing.',
    'about.title2': 'Into Growth.',
    'about.subtitle': 'We\'re not your typical digital marketing agency. DevHelp is a growth accelerator that transforms ambitious ideas into market-leading realities through strategic innovation and flawless execution.',
    'about.feature1.title': 'Strategic Growth',
    'about.feature1.desc': 'We don\'t just execute — we strategize. Every decision is backed by data and focused on measurable growth.',
    'about.feature2.title': 'Innovation First',
    'about.feature2.desc': 'Cutting-edge solutions that set you apart from the competition. We turn your vision into digital reality.',
    'about.feature3.title': 'Results-Driven',
    'about.feature3.desc': 'Every project is measured by impact. We deliver solutions that drive real business transformation.',
    'about.feature4.title': 'Growth Acceleration',
    'about.feature4.desc': 'From concept to scale — we accelerate your journey with proven methodologies and expert execution.',
    'about.story.title': 'Transformation Through Innovation',
    'about.story.p1': 'At DevHelp, we believe in the power of transformation. Every business has untapped potential, and our role is to unlock it through strategic digital solutions that don\'t just market — they accelerate.',
    'about.story.p2': 'Our approach combines deep market insights, cutting-edge technology, and growth-focused execution to deliver results that matter. We\'re your partners in building the future.',
    
    // Services Section
    'services.title': 'Our',
    'services.titleHighlight': 'Acceleration',
    'services.titleEnd': 'Programs',
    'services.subtitle': 'We don\'t just deliver services — we deliver transformation. Each program is designed to accelerate your growth and turn your vision into measurable results.',
    'services.cta.title': 'Ready to Accelerate Your Growth?',
    'services.cta.subtitle': 'Let\'s discuss how our acceleration programs can transform your business. Book a discovery call and start your growth journey today.',
    'services.cta.button': 'Start Your Acceleration',
    
    // Services Section - Individual Services
    'services.service1.title': 'From Idea to MVP',
    'services.service1.desc': 'Transform your vision into a market-ready product. We guide you through every step from concept validation to launch.',
    'services.service1.feature1': 'Strategy & Planning',
    'services.service1.feature2': 'MVP Development',
    'services.service1.feature3': 'Market Testing',
    'services.service1.feature4': 'Launch Support',
    'services.service2.title': 'Growth-Focused Web Dev',
    'services.service2.desc': 'High-performance websites and applications built for conversion and scalability. Every line of code drives growth.',
    'services.service2.feature1': 'Custom Development',
    'services.service2.feature2': 'Performance Optimization',
    'services.service2.feature3': 'Conversion Focus',
    'services.service2.feature4': 'Mobile-First Design',
    'services.service3.title': 'Digital Transformation',
    'services.service3.desc': 'Modernize your digital presence with cutting-edge solutions that position you ahead of the competition.',
    'services.service3.feature1': 'Process Automation',
    'services.service3.feature2': 'System Integration',
    'services.service3.feature3': 'Digital Strategy',
    'services.service3.feature4': 'Technology Consulting',
    'services.service4.title': 'Growth Analytics',
    'services.service4.desc': 'Data-driven insights that fuel smart decisions. We turn your data into actionable growth strategies.',
    'services.service4.feature1': 'Performance Tracking',
    'services.service4.feature2': 'Growth Metrics',
    'services.service4.feature3': 'ROI Analysis',
    'services.service4.feature4': 'Strategic Insights',
    'services.service5.title': 'Scalable Infrastructure',
    'services.service5.desc': 'Build for the future with infrastructure that grows with your business. No limits, just possibilities.',
    'services.service5.feature1': 'Cloud Solutions',
    'services.service5.feature2': 'Performance Scaling',
    'services.service5.feature3': 'Security First',
    'services.service5.feature4': 'Future-Proof Tech',
    'services.service6.title': 'Mobile Excellence',
    'services.service6.desc': 'Mobile-first experiences that engage and convert. Your audience is mobile — your solution should be too.',
    'services.service6.feature1': 'Responsive Design',
    'services.service6.feature2': 'Mobile Apps',
    'services.service6.feature3': 'PWA Development',
    'services.service6.feature4': 'Cross-Platform',

    // Results Section
    'results.title1': 'Real Results.',
    'results.title2': 'Real Impact.',
    'results.subtitle': 'Our success is measured by your growth. Here\'s the proof that our acceleration approach delivers transformational results for businesses of all sizes.',
    'results.stat1.number': '300%',
    'results.stat1.label': 'Average Growth Increase',
    'results.stat1.desc': 'Our clients see significant growth within the first 6 months',
    'results.stat2.number': '150+',
    'results.stat2.label': 'Businesses Accelerated',
    'results.stat2.desc': 'From startups to enterprises, we\'ve powered their growth',
    'results.stat3.number': '48h',
    'results.stat3.label': 'Average Response Time',
    'results.stat3.desc': 'Quick turnaround on projects and communications',
    'results.stat4.number': '95%',
    'results.stat4.label': 'Client Satisfaction',
    'results.stat4.desc': 'Long-term partnerships built on results and trust',
    'results.caseStudies.title': 'Success Stories',
    'results.case1.title': 'E-commerce Revolution',
    'results.case1.client': 'Fashion Startup',
    'results.case1.result': '400% Revenue Growth',
    'results.case1.desc': 'Transformed a small fashion brand into a market leader with strategic web development and growth optimization.',
    'results.case1.metric1': '400% revenue increase',
    'results.case1.metric2': '250% traffic growth',
    'results.case1.metric3': '60% conversion improvement',
    'results.case1.category': 'E-commerce',
    'results.case2.title': 'SaaS Acceleration',
    'results.case2.client': 'Tech Company',
    'results.case2.result': '10x User Acquisition',
    'results.case2.desc': 'Scaled a B2B SaaS platform from 1K to 10K users through strategic digital transformation and optimization.',
    'results.case2.metric1': '10x user growth',
    'results.case2.metric2': '300% retention rate',
    'results.case2.metric3': '50% cost reduction',
    'results.case2.category': 'SaaS',
    'results.case3.title': 'Digital Transformation',
    'results.case3.client': 'Manufacturing Firm',
    'results.case3.result': '200% Efficiency Gain',
    'results.case3.desc': 'Modernized operations with custom solutions, resulting in streamlined processes and significant cost savings.',
    'results.case3.metric1': '200% efficiency gain',
    'results.case3.metric2': '40% cost reduction',
    'results.case3.metric3': '90% automation',
    'results.case3.category': 'Enterprise',
    'results.team.quote': 'DevHelp didn\'t just build us a website — they accelerated our entire business. Their strategic approach and innovative solutions transformed how we operate and grow.',
    'results.team.person1.name': 'Mouad EL OTMANI',
    'results.team.person1.title': 'CEO, DevHelp',
    'results.team.person2.name': 'Youness TAFTAF',
    'results.team.person2.title': 'Co-Founder, DevHelp',

    // FAQ Section
    'faq.title1': 'Frequently Asked',
    'faq.title2': 'Questions',
    'faq.subtitle': 'Everything you need to know about our services, pricing, and how we can accelerate your growth.',
    'faq.q1': 'What does a "Growth Accelerator" mean?',
    'faq.a1': 'We don\'t just build websites; we create digital ecosystems designed to convert, scale, and accelerate your business growth through strategic design and development.',
    'faq.q2': 'How long does it take to build a website?',
    'faq.a2': 'Depending on the complexity, our Business Pack usually takes 1-2 weeks to launch, while a Premium Pack can take 3-4 weeks from initial strategy to final deployment.',
    'faq.q3': 'Do you provide ongoing support after the launch?',
    'faq.a3': 'Yes! Our Premium Pack includes 60 days of dedicated support and maintenance to ensure everything runs perfectly smoothly while you scale your business.',
    'faq.q4': 'Can you help us if we already have a website?',
    'faq.a4': 'Absolutely. We perform a complete digital audit to identify bottlenecks, and then rebuild or optimize your current platform for significantly better performance and conversions.',
    'faq.q5': 'Do you handle the hosting and domain name?',
    'faq.a5': 'Yes, both of our packs include a free .com or .ma domain and fast, secure cloud hosting for the entire first year.',

    // Contact Section
    'contact.title1': 'Let\'s Build the',
    'contact.title2': 'Future Together',
    'contact.subtitle': 'Ready to accelerate your growth? Let\'s discuss how we can transform your ideas into measurable results. Your success story starts with a conversation.',
    'contact.form.title': 'Start Your Project',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.budget': 'Project Type',
    'contact.form.budgetSelect': 'Enter your project type...',
    'contact.form.message': 'Project Details',
    'contact.form.messagePlaceholder': 'Tell us about your project, goals, and how we can help accelerate your growth...',
    'contact.form.send': 'Send Message',
    'contact.info.title': 'Get In Touch',
    'contact.info.email': 'Email Us',
    'contact.info.phone': 'Call Us',
    'contact.info.response': 'Response Time',
    'contact.info.responseTime': 'Within 48 hours',
    'contact.quickActions': 'Quick Actions',
    'contact.actions.book': 'Book Discovery Call',
    'contact.actions.call': 'Call Now',
    'contact.actions.email': 'Email Directly',
    'contact.ready.title': 'Ready to Accelerate?',
    'contact.ready.subtitle': 'Join 150+ businesses that have transformed their growth with DevHelp.',
    'contact.ready.button': 'Let\'s Start Today',
    
    // Packs Section
    'packs.title1': 'Creative Services Package Adapted to ',
    'packs.title2': 'Your Business',
    'packs.pack1.name': 'BUSINESS PACK',
    'packs.pack1.target': 'Adapted to: Small businesses, local businesses, personal portfolios.',
    'packs.pack1.price': ' ',
    'packs.pack1.feature1': 'Adaptive Design (Computer + Mobile + Tablet).',
    'packs.pack1.feature2': 'Up to 3 pages (Homepage | About | Contact Us).',
    'packs.pack1.feature3': 'Free .com or .ma domain for one year.',
    'packs.pack1.feature4': 'Fast hosting for one year.',
    'packs.pack1.feature5': 'SSL Certificate.',
    'packs.pack1.feature6': 'Basic SEO Configuration (Titles + Meta).',
    'packs.pack2.name': 'PACK PREMIUM',
    'packs.pack2.target': 'Adapted to: Medium enterprises, associations, educational privileges.',
    'packs.pack2.price': ' ',
    'packs.pack2.feature1': 'Up to 6 pages (Home - About - Services - Blog - Contact - Extra page).',
    'packs.pack2.feature2': 'Domain and hosting for one year.',
    'packs.pack2.feature3': 'SSL Certificate.',
    'packs.pack2.feature4': 'Complete SEO Optimization (Google Maps, videos, primary keywords).',
    'packs.pack2.feature5': 'Support and maintenance: 60 days.',
    'packs.pack2.feature6': 'Short training (video/conference) on content management.',
  },
  
  fr: {
    // Navigation
    'nav.about': 'À Propos',
    'nav.packs': 'Les Packs',
    'nav.services': 'Services',
    'nav.results': 'Résultats',
    'nav.contact': 'Contact',
    'nav.bookCall': 'Réserver un Appel',
    
    // Hero Section
    'hero.badge': 'Accélérateur de Croissance',
    'hero.title1': 'Nous Ne Faisons Pas De',
    'hero.title2': 'Marketing',
    'hero.title3': 'Nous',
    'hero.title4': 'Accélérons la Croissance.',
    'hero.subtitle': 'DevHelp transforme vos idées en résultats concrets grâce à des solutions web innovantes, des conseils stratégiques et un état d\'esprit axé sur la performance. Nous ne sommes pas juste une autre agence — nous sommes votre partenaire de croissance.',
    'hero.cta1': 'Accélérons Ensemble',
    'hero.cta2': 'Réserver un Appel',
    
    // About Section
    'about.title1': 'Au-delà du Marketing.',
    'about.title2': 'Vers la Croissance.',
    'about.subtitle': 'Nous ne sommes pas votre agence de marketing digital typique. DevHelp est un accélérateur de croissance qui transforme les idées ambitieuses en réalités leaders du marché grâce à l\'innovation stratégique et une exécution parfaite.',
    'about.feature1.title': 'Croissance Stratégique',
    'about.feature1.desc': 'Nous ne nous contentons pas d\'exécuter — nous stratégisons. Chaque décision est soutenue par des données et axée sur une croissance mesurable.',
    'about.feature2.title': 'Innovation Avant Tout',
    'about.feature2.desc': 'Des solutions de pointe qui vous distinguent de la concurrence. Nous transformons votre vision en réalité numérique.',
    'about.feature3.title': 'Axé sur les Résultats',
    'about.feature3.desc': 'Chaque projet est mesuré par son impact. Nous livrons des solutions qui conduisent à une vraie transformation d\'entreprise.',
    'about.feature4.title': 'Accélération de Croissance',
    'about.feature4.desc': 'Du concept à l\'échelle — nous accélérons votre parcours avec des méthodologies éprouvées et une exécution experte.',
    'about.story.title': 'Transformation par l\'Innovation',
    'about.story.p1': 'Chez DevHelp, nous croyons au pouvoir de la transformation. Chaque entreprise a un potentiel inexploité, et notre rôle est de le libérer grâce à des solutions numériques stratégiques qui n\'font pas que du marketing — elles accélèrent.',
    'about.story.p2': 'Notre approche combine des insights de marché profonds, une technologie de pointe et une exécution axée sur la croissance pour livrer des résultats qui comptent. Nous sommes vos partenaires dans la construction de l\'avenir.',
    
    // Services Section
    'services.title': 'Nos Programmes d\'',
    'services.titleHighlight': 'Accélération',
    'services.titleEnd': '',
    'services.subtitle': 'Nous ne livrons pas juste des services — nous livrons la transformation. Chaque programme est conçu pour accélérer votre croissance et transformer votre vision en résultats mesurables.',
    'services.cta.title': 'Prêt à Accélérer Votre Croissance ?',
    'services.cta.subtitle': 'Discutons de comment nos programmes d\'accélération peuvent transformer votre entreprise. Réservez un appel de découverte et commencez votre parcours de croissance aujourd\'hui.',
    'services.cta.button': 'Commencer Votre Accélération',
    
    // Services Section - Individual Services
    'services.service1.title': 'De l\'Idée au MVP',
    'services.service1.desc': 'Transformez votre vision en produit prêt pour le marché. Nous vous guidons à chaque étape de la validation du concept au lancement.',
    'services.service1.feature1': 'Stratégie et Planification',
    'services.service1.feature2': 'Développement MVP',
    'services.service1.feature3': 'Tests de Marché',
    'services.service1.feature4': 'Support de Lancement',
    'services.service2.title': 'Développement Web Axé Croissance',
    'services.service2.desc': 'Sites web et applications haute performance conçus pour la conversion et l\'évolutivité. Chaque ligne de code favorise la croissance.',
    'services.service2.feature1': 'Développement Personnalisé',
    'services.service2.feature2': 'Optimisation des Performances',
    'services.service2.feature3': 'Focus sur la Conversion',
    'services.service2.feature4': 'Design Mobile-First',
    'services.service3.title': 'Transformation Numérique',
    'services.service3.desc': 'Modernisez votre présence numérique avec des solutions de pointe qui vous positionnent en avance sur la concurrence.',
    'services.service3.feature1': 'Automatisation des Processus',
    'services.service3.feature2': 'Intégration Systèmes',
    'services.service3.feature3': 'Stratégie Numérique',
    'services.service3.feature4': 'Conseil Technologique',
    'services.service4.title': 'Analytique de Croissance',
    'services.service4.desc': 'Insights basés sur les données qui alimentent des décisions intelligentes. Nous transformons vos données en stratégies de croissance actionables.',
    'services.service4.feature1': 'Suivi des Performances',
    'services.service4.feature2': 'Métriques de Croissance',
    'services.service4.feature3': 'Analyse ROI',
    'services.service4.feature4': 'Insights Stratégiques',
    'services.service5.title': 'Infrastructure Évolutive',
    'services.service5.desc': 'Construisez pour l\'avenir avec une infrastructure qui grandit avec votre entreprise. Pas de limites, que des possibilités.',
    'services.service5.feature1': 'Solutions Cloud',
    'services.service5.feature2': 'Mise à l\'Échelle des Performances',
    'services.service5.feature3': 'Sécurité d\'Abord',
    'services.service5.feature4': 'Technologie Future-Proof',
    'services.service6.title': 'Excellence Mobile',
    'services.service6.desc': 'Expériences mobile-first qui engagent et convertissent. Votre audience est mobile — votre solution devrait l\'être aussi.',
    'services.service6.feature1': 'Design Responsive',
    'services.service6.feature2': 'Applications Mobile',
    'services.service6.feature3': 'Développement PWA',
    'services.service6.feature4': 'Cross-Platform',

    // Results Section
    'results.title1': 'Vrais Résultats.',
    'results.title2': 'Vrai Impact.',
    'results.subtitle': 'Notre succès se mesure par votre croissance. Voici la preuve que notre approche d\'accélération offre des résultats transformationnels pour les entreprises de toutes tailles.',
    'results.stat1.number': '300%',
    'results.stat1.label': 'Augmentation Moyenne de Croissance',
    'results.stat1.desc': 'Nos clients voient une croissance significative dans les 6 premiers mois',
    'results.stat2.number': '150+',
    'results.stat2.label': 'Entreprises Accélérées',
    'results.stat2.desc': 'Des startups aux entreprises, nous avons alimenté leur croissance',
    'results.stat3.number': '48h',
    'results.stat3.label': 'Temps de Réponse Moyen',
    'results.stat3.desc': 'Turnaround rapide sur les projets et communications',
    'results.stat4.number': '95%',
    'results.stat4.label': 'Satisfaction Client',
    'results.stat4.desc': 'Partenariats long terme basés sur les résultats et la confiance',
    'results.caseStudies.title': 'Histoires de Succès',
    'results.case1.title': 'Révolution E-commerce',
    'results.case1.client': 'Startup Mode',
    'results.case1.result': '400% Croissance Chiffre d\'Affaires',
    'results.case1.desc': 'Transformé une petite marque de mode en leader du marché avec développement web stratégique et optimisation de croissance.',
    'results.case1.metric1': '400% augmentation chiffre d\'affaires',
    'results.case1.metric2': '250% croissance trafic',
    'results.case1.metric3': '60% amélioration conversion',
    'results.case1.category': 'E-commerce',
    'results.case2.title': 'Accélération SaaS',
    'results.case2.client': 'Entreprise Tech',
    'results.case2.result': '10x Acquisition Utilisateurs',
    'results.case2.desc': 'Mis à l\'échelle une plateforme SaaS B2B de 1K à 10K utilisateurs grâce à la transformation numérique stratégique et l\'optimisation.',
    'results.case2.metric1': '10x croissance utilisateurs',
    'results.case2.metric2': '300% taux de rétention',
    'results.case2.metric3': '50% réduction coûts',
    'results.case2.category': 'SaaS',
    'results.case3.title': 'Transformation Numérique',
    'results.case3.client': 'Entreprise Manufacturière',
    'results.case3.result': '200% Gain d\'Efficacité',
    'results.case3.desc': 'Modernisé les opérations avec des solutions personnalisées, résultant en processus rationalisés et économies significatives.',
    'results.case3.metric1': '200% gain d\'efficacité',
    'results.case3.metric2': '40% réduction coûts',
    'results.case3.metric3': '90% automatisation',
    'results.case3.category': 'Entreprise',
    'results.team.quote': 'DevHelp n\'a pas seulement créé un site web — ils ont accéléré toute notre entreprise. Leur approche stratégique et leurs solutions innovantes ont transformé notre façon de fonctionner et de croître.',
    'results.team.person1.name': 'Mouad EL OTMANI',
    'results.team.person1.title': 'PDG, DevHelp',
    'results.team.person2.name': 'Youness TAFTAF',
    'results.team.person2.title': 'Co-Fondateur, DevHelp',
    
    // FAQ Section
    'faq.title1': 'Questions',
    'faq.title2': 'Fréquentes',
    'faq.subtitle': 'Tout ce que vous devez savoir sur nos services, nos tarifs et comment nous pouvons accélérer votre croissance.',
    'faq.q1': 'Que signifie un "Accélérateur de Croissance" ?',
    'faq.a1': 'Nous ne créons pas seulement des sites web ; nous créons des écosystèmes numériques conçus pour convertir, évoluer et accélérer la croissance de votre entreprise grâce au design stratégique.',
    'faq.q2': 'Combien de temps faut-il pour créer un site web ?',
    'faq.a2': 'Selon la complexité, notre Pack Business prend généralement 1 à 2 semaines, tandis qu\'un Pack Premium peut prendre 3 à 4 semaines de la stratégie initiale au lancement.',
    'faq.q3': 'Fournissez-vous un support continu après le lancement ?',
    'faq.a3': 'Oui ! Notre Pack Premium comprend 60 jours de support et de maintenance dédiés pour garantir que tout fonctionne parfaitement pendant que vous développez votre entreprise.',
    'faq.q4': 'Pouvez-vous nous aider si nous avons déjà un site web ?',
    'faq.a4': 'Absolument. Nous effectuons un audit numérique complet pour identifier les problèmes, puis nous reconstruisons ou optimisons votre plateforme actuelle pour de meilleures conversions.',
    'faq.q5': 'Gérez-vous l\'hébergement et le nom de domaine ?',
    'faq.a5': 'Oui, nos deux packs incluent un domaine .com ou .ma gratuit et un hébergement cloud rapide et sécurisé pour toute la première année.',

    // Contact Section
    'contact.title1': 'Construisons l\'',
    'contact.title2': 'Avenir Ensemble',
    'contact.subtitle': 'Prêt à accélérer votre croissance ? Discutons de comment nous pouvons transformer vos idées en résultats mesurables. Votre histoire de succès commence par une conversation.',
    'contact.form.title': 'Commencer Votre Projet',
    'contact.form.name': 'Nom Complet',
    'contact.form.email': 'Adresse Email',
    'contact.form.budget': 'Type de Projet',
    'contact.form.budgetSelect': 'Entrez le type de votre projet...',
    'contact.form.message': 'Détails du Projet',
    'contact.form.messagePlaceholder': 'Parlez-nous de votre projet, de vos objectifs et de comment nous pouvons aider à accélérer votre croissance...',
    'contact.form.send': 'Envoyer le Message',
    'contact.info.title': 'Entrer en Contact',
    'contact.info.email': 'Nous Écrire',
    'contact.info.phone': 'Nous Appeler',
    'contact.info.response': 'Temps de Réponse',
    'contact.info.responseTime': 'Sous 48 heures',
    'contact.quickActions': 'Actions Rapides',
    'contact.actions.book': 'Réserver un Appel',
    'contact.actions.call': 'Appeler Maintenant',
    'contact.actions.email': 'Email Direct',
    'contact.ready.title': 'Prêt à Accélérer ?',
    'contact.ready.subtitle': 'Rejoignez 150+ entreprises qui ont transformé leur croissance avec DevHelp.',
    'contact.ready.button': 'Commençons Aujourd\'hui',
    
    // Packs Section
    'packs.title1': 'Forfait de Services Créatifs Adapté à ',
    'packs.title2': 'Votre Entreprise',
    'packs.pack1.name': 'BUSINESS PACK',
    'packs.pack1.target': 'Adapté pour : Petites entreprises, commerces locaux, portfolios personnels.',
    'packs.pack1.price': ' ',
    'packs.pack1.feature1': 'Design Adaptatif (Ordinateur + Mobile + Tablette).',
    'packs.pack1.feature2': 'Jusqu\'à 3 pages (Accueil | À propos | Contact).',
    'packs.pack1.feature3': 'Domaine .com ou .ma gratuit pendant un an.',
    'packs.pack1.feature4': 'Hébergement rapide pendant un an.',
    'packs.pack1.feature5': 'Certificat SSL.',
    'packs.pack1.feature6': 'Configuration SEO de base (Titres + Meta).',
    'packs.pack2.name': 'PACK PREMIUM',
    'packs.pack2.target': 'Adapté pour : Moyennes entreprises, associations, privilèges éducatifs.',
    'packs.pack2.price': ' ',
    'packs.pack2.feature1': 'Jusqu\'à 6 pages (Accueil - À propos - Services - Blog - Nous contacter - Page supplémentaire).',
    'packs.pack2.feature2': 'Domaine et hébergement pendant un an.',
    'packs.pack2.feature3': 'Certificat SSL.',
    'packs.pack2.feature4': 'Optimisation SEO complète (Google Maps, vidéos, mots-clés principaux).',
    'packs.pack2.feature5': 'Support et maintenance : 60 jours.',
    'packs.pack2.feature6': 'Formation courte (vidéo/conférence) sur la gestion du contenu.',
  },
  
  ar: {
    // Navigation
    'nav.about': 'حولنا',
    'nav.packs': 'الباقات',
    'nav.services': 'الخدمات',
    'nav.results': 'النتائج',
    'nav.contact': 'تواصل معنا',
    'nav.bookCall': 'احجز مكالمة',
    
    // Hero Section
    'hero.badge': 'مُسرِّع النمو',
    'hero.title1': 'نحن لا نقوم بـ',
    'hero.title2': 'التسويق',
    'hero.title3': 'نحن',
    'hero.title4': 'نُسرِّع النمو.',
    'hero.subtitle': 'DevHelp تحول أفكارك إلى نتائج حقيقية من خلال حلول الويب المبتكرة والإرشاد الاستراتيجي والعقلية المرتكزة على الأداء. نحن لسنا مجرد وكالة أخرى — نحن شريك النمو الخاص بك.',
    'hero.cta1': 'لنُسرِّع معاً',
    'hero.cta2': 'احجز مكالمة',
    
    // About Section
    'about.title1': 'ما وراء التسويق.',
    'about.title2': 'نحو النمو.',
    'about.subtitle': 'نحن لسنا وكالة التسويق الرقمي النموذجية. DevHelp هو مُسرِّع نمو يحول الأفكار الطموحة إلى حقائق رائدة في السوق من خلال الابتكار الاستراتيجي والتنفيذ المثالي.',
    'about.feature1.title': 'النمو الاستراتيجي',
    'about.feature1.desc': 'نحن لا نكتفي بالتنفيذ — نحن نضع الاستراتيجيات. كل قرار مدعوم بالبيانات ومركز على النمو القابل للقياس.',
    'about.feature2.title': 'الابتكار أولاً',
    'about.feature2.desc': 'حلول متطورة تميزك عن المنافسة. نحول رؤيتك إلى واقع رقمي.',
    'about.feature3.title': 'مدفوع بالنتائج',
    'about.feature3.desc': 'كل مشروع يُقاس بتأثيره. نقدم حلولاً تقود التحول الحقيقي للأعمال.',
    'about.feature4.title': 'تسريع النمو',
    'about.feature4.desc': 'من المفهوم إلى النطاق — نُسرِّع رحلتك بمنهجيات مثبتة وتنفيذ خبير.',
    'about.story.title': 'التحول من خلال الابتكار',
    'about.story.p1': 'في DevHelp، نؤمن بقوة التحول. كل عمل لديه إمكانات غير مستغلة، ودورنا هو إطلاقها من خلال حلول رقمية استراتيجية لا تكتفي بالتسويق — بل تُسرِّع.',
    'about.story.p2': 'نهجنا يجمع بين رؤى السوق العميقة والتكنولوجيا المتطورة والتنفيذ المركز على النمو لتقديم نتائج مهمة. نحن شركاؤك في بناء المستقبل.',
    
    // Services Section
    'services.title': 'برامج',
    'services.titleHighlight': 'التسريع',
    'services.titleEnd': 'الخاصة بنا',
    'services.subtitle': 'نحن لا نقدم الخدمات فقط — نقدم التحول. كل برنامج مصمم لتسريع نموك وتحويل رؤيتك إلى نتائج قابلة للقياس.',
    'services.cta.title': 'مستعد لتسريع نموك؟',
    'services.cta.subtitle': 'دعنا نناقش كيف يمكن لبرامج التسريع لدينا تحويل عملك. احجز مكالمة اكتشاف وابدأ رحلة نموك اليوم.',
    'services.cta.button': 'ابدأ تسريعك',
    
    // Services Section - Individual Services
    'services.service1.title': 'من الفكرة إلى MVP',
    'services.service1.desc': 'حول رؤيتك إلى منتج جاهز للسوق. نحن نرشدك خلال كل خطوة من التحقق من المفهوم إلى الإطلاق.',
    'services.service1.feature1': 'الاستراتيجية والتخطيط',
    'services.service1.feature2': 'تطوير MVP',
    'services.service1.feature3': 'اختبار السوق',
    'services.service1.feature4': 'دعم الإطلاق',
    'services.service2.title': 'تطوير ويب مركز على النمو',
    'services.service2.desc': 'مواقع الويب والتطبيقات عالية الأداء المصممة للتحويل وقابلية التطوير. كل سطر من الكود يدفع النمو.',
    'services.service2.feature1': 'التطوير المخصص',
    'services.service2.feature2': 'تحسين الأداء',
    'services.service2.feature3': 'التركيز على التحويل',
    'services.service2.feature4': 'التصميم Mobile-First',
    'services.service3.title': 'التحول الرقمي',
    'services.service3.desc': 'حدث حضورك الرقمي بحلول متطورة تضعك قبل المنافسة.',
    'services.service3.feature1': 'أتمتة العمليات',
    'services.service3.feature2': 'تكامل الأنظمة',
    'services.service3.feature3': 'الاستراتيجية الرقمية',
    'services.service3.feature4': 'الاستشارات التقنية',
    'services.service4.title': 'تحليلات النمو',
    'services.service4.desc': 'رؤى مدفوعة بالبيانات تغذي القرارات الذكية. نحن نحول بياناتك إلى استراتيجيات نمو قابلة للتنفيذ.',
    'services.service4.feature1': 'تتبع الأداء',
    'services.service4.feature2': 'مقاييس النمو',
    'services.service4.feature3': 'تحليل العائد على الاستثمار',
    'services.service4.feature4': 'الرؤى الاستراتيجية',
    'services.service5.title': 'البنية التحتية القابلة للتطوير',
    'services.service5.desc': 'ابن للمستقبل ببنية تحتية تنمو مع عملك. لا حدود، فقط إمكانيات.',
    'services.service5.feature1': 'حلول السحابة',
    'services.service5.feature2': 'تطوير الأداء',
    'services.service5.feature3': 'الأمان أولاً',
    'services.service5.feature4': 'تقنية مستقبلية',
    'services.service6.title': 'التميز المحمول',
    'services.service6.desc': 'تجارب mobile-first تشرك وتحول. جمهورك محمول — حلك يجب أن يكون كذلك أيضاً.',
    'services.service6.feature1': 'التصميم المتجاوب',
    'services.service6.feature2': 'تطبيقات الهاتف المحمول',
    'services.service6.feature3': 'تطوير PWA',
    'services.service6.feature4': 'متعدد المنصات',

    // Results Section
    'results.title1': 'نتائج حقيقية.',
    'results.title2': 'تأثير حقيقي.',
    'results.subtitle': 'نجاحنا يُقاس بنموك. إليك الدليل على أن نهج التسريع لدينا يحقق نتائج تحويلية للشركات من جميع الأحجام.',
    'results.stat1.number': '300%',
    'results.stat1.label': 'متوسط زيادة النمو',
    'results.stat1.desc': 'عملاؤنا يرون نمواً كبيراً خلال أول 6 أشهر',
    'results.stat2.number': '150+',
    'results.stat2.label': 'الشركات المُسرَّعة',
    'results.stat2.desc': 'من الشركات الناشئة إلى المؤسسات، لقد قمنا بتعزيز نموها',
    'results.stat3.number': '48 ساعة',
    'results.stat3.label': 'متوسط وقت الاستجابة',
    'results.stat3.desc': 'تنفيذ سريع للمشاريع والاتصالات',
    'results.stat4.number': '95%',
    'results.stat4.label': 'رضا العملاء',
    'results.stat4.desc': 'شراكات طويلة الأمد مبنية على النتائج والثقة',
    'results.caseStudies.title': 'قصص النجاح',
    'results.case1.title': 'ثورة التجارة الإلكترونية',
    'results.case1.client': 'شركة أزياء ناشئة',
    'results.case1.result': '400% نمو في الإيرادات',
    'results.case1.desc': 'حولت علامة أزياء صغيرة إلى رائدة في السوق من خلال التطوير الاستراتيجي للويب وتحسين النمو.',
    'results.case1.metric1': '400% زيادة في الإيرادات',
    'results.case1.metric2': '250% نمو في حركة المرور',
    'results.case1.metric3': '60% تحسن في التحويل',
    'results.case1.category': 'التجارة الإلكترونية',
    'results.case2.title': 'تسريع SaaS',
    'results.case2.client': 'شركة تقنية',
    'results.case2.result': '10 أضعاف اكتساب المستخدمين',
    'results.case2.desc': 'توسعت منصة SaaS للشركات من 1000 إلى 10000 مستخدم من خلال التحول الرقمي الاستراتيجي والتحسين.',
    'results.case2.metric1': '10 أضعاف نمو المستخدمين',
    'results.case2.metric2': '300% معدل الاحتفاظ',
    'results.case2.metric3': '50% تقليل التكاليف',
    'results.case2.category': 'SaaS',
    'results.case3.title': 'التحول الرقمي',
    'results.case3.client': 'شركة تصنيع',
    'results.case3.result': '200% مكسب في الكفاءة',
    'results.case3.desc': 'حدثت العمليات بحلول مخصصة، مما أدى إلى عمليات مبسطة ووفورات كبيرة في التكاليف.',
    'results.case3.metric1': '200% مكسب في الكفاءة',
    'results.case3.metric2': '40% تقليل التكاليف',
    'results.case3.metric3': '90% أتمتة',
    'results.case3.category': 'المؤسسة',
    'results.team.quote': 'DevHelp لم تبنِ لنا موقعاً فحسب — بل سرّعت أعمالنا بالكامل. نهجهم الاستراتيجي وحلولهم المبتكرة غيّرت طريقة عملنا ونمونا.',
    'results.team.person1.name': 'معاذ العثماني',
    'results.team.person1.title': 'الرئيس التنفيذي، DevHelp',
    'results.team.person2.name': 'يونس تفتاف',
    'results.team.person2.title': 'المؤسس المشارك، DevHelp',
    
    // FAQ Section
    'faq.title1': 'الأسئلة',
    'faq.title2': 'الشائعة',
    'faq.subtitle': 'كل ما تحتاج لمعرفته حول خدماتنا وأسعارنا وكيف يمكننا تسريع نموك.',
    'faq.q1': 'ماذا يعني "مُسرِّع النمو"؟',
    'faq.a1': 'نحن لا نبني مواقع الويب فحسب؛ بل ننشئ أنظمة رقمية مصممة للتحويل والتوسع وتسريع نمو عملك من خلال التصميم والتطوير الاستراتيجي.',
    'faq.q2': 'كم يستغرق بناء موقع ويب؟',
    'faq.a2': 'اعتمادًا على التعقيد، تستغرق باقة الأعمال عادةً أسبوعًا إلى أسبوعين، بينما تستغرق الباقة المميزة 3-4 أسابيع من الاستراتيجية الأولية حتى الإطلاق النهائي.',
    'faq.q3': 'هل تقدمون الدعم المستمر بعد الإطلاق؟',
    'faq.a3': 'نعم! تتضمن باقتنا المميزة 60 يومًا من الدعم والصيانة المخصصة لضمان سير كل شيء بسلاسة تامة.',
    'faq.q4': 'هل يمكنكم مساعدتنا إذا كان لدينا موقع بالفعل؟',
    'faq.a4': 'بالتأكيد. نقوم بإجراء تدقيق رقمي كامل لتحديد العقبات، ثم نقوم بإعادة بناء أو تحسين منصتك الحالية لزيادة الأداء والتحويلات بشكل كبير.',
    'faq.q5': 'هل تتولون إدارة الاستضافة واسم النطاق؟',
    'faq.a5': 'نعم، تتضمن كلتا باقتينا نطاق .com أو .ma مجانيًا واستضافة سحابية سريعة وآمنة للعام الأول بأكمله.',

    // Contact Section
    'contact.title1': 'لنبني',
    'contact.title2': 'المستقبل معاً',
    'contact.subtitle': 'مستعد لتسريع نموك؟ دعنا نناقش كيف يمكننا تحويل أفكارك إلى نتائج قابلة للقياس. قصة نجاحك تبدأ بمحادثة.',
    'contact.form.title': 'ابدأ مشروعك',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.budget': 'نوع المشروع',
    'contact.form.budgetSelect': 'أدخل نوع مشروعك...',
    'contact.form.message': 'تفاصيل المشروع',
    'contact.form.messagePlaceholder': 'أخبرنا عن مشروعك وأهدافك وكيف يمكننا مساعدتك في تسريع نموك...',
    'contact.form.send': 'إرسال الرسالة',
    'contact.info.title': 'تواصل معنا',
    'contact.info.email': 'راسلنا',
    'contact.info.phone': 'اتصل بنا',
    'contact.info.response': 'وقت الاستجابة',
    'contact.info.responseTime': 'خلال 48 ساعة',
    'contact.quickActions': 'إجراءات سريعة',
    'contact.actions.book': 'احجز مكالمة',
    'contact.actions.call': 'اتصل الآن',
    'contact.actions.email': 'بريد مباشر',
    'contact.ready.title': 'مستعد للتسريع؟',
    'contact.ready.subtitle': 'انضم إلى 150+ شركة حولت نموها مع DevHelp.',
    'contact.ready.button': 'لنبدأ اليوم',
    
    // Packs Section
    'packs.title1': 'باقات خدمات إبداعية مصممة خصيصاً لـ ',
    'packs.title2': 'عملك',
    'packs.pack1.name': 'باقة الأعمال',
    'packs.pack1.target': 'مناسبة لـ: الشركات الصغيرة، الأعمال المحلية، والمحافظ الشخصية.',
    'packs.pack1.price': ' ',
    'packs.pack1.feature1': 'تصميم متجاوب (كمبيوتر + هاتف + جهاز لوحي).',
    'packs.pack1.feature2': 'إلى حد 3 صفحات (الرئيسية | من نحن | اتصل بنا).',
    'packs.pack1.feature3': 'نطاق .com أو .ma مجاني لمدة عام.',
    'packs.pack1.feature4': 'استضافة سريعة لمدة عام.',
    'packs.pack1.feature5': 'شهادة SSL.',
    'packs.pack1.feature6': 'إعداد SEO الأساسي (العناوين + الميتا).',
    'packs.pack2.name': 'الباقة المميزة',
    'packs.pack2.target': 'مناسبة لـ: الشركات المتوسطة، الجمعيات، المؤسسات التعليمية.',
    'packs.pack2.price': ' ',
    'packs.pack2.feature1': 'إلى حد 6 صفحات (الرئيسية - من نحن - الخدمات - المدونة - اتصل بنا - صفحة إضافية).',
    'packs.pack2.feature2': 'نطاق واستضافة لمدة عام.',
    'packs.pack2.feature3': 'شهادة SSL.',
    'packs.pack2.feature4': 'تحسين SEO الشامل (خرائط جوجل، مقاطع فيديو، كلمات مفتاحية رئيسية).',
    'packs.pack2.feature5': 'تحديث وصيانة: 60 يوماً.',
    'packs.pack2.feature6': 'تدريب قصير (فيديو/مؤتمر) على إدارة المحتوى.',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Check for saved language preference
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'fr', 'ar'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    
    // Update document direction for Arabic
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage: handleSetLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};